"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, ChevronRight, LayoutDashboard, MousePointer2, Search, ShieldCheck, Smartphone, UserPlus, Zap } from "lucide-react";

export default function UserGuide() {
  const steps = [
    {
      title: "Onboarding & Access",
      icon: UserPlus,
      content: "Start by creating an account or logging in via the 'Sign Up' page. This gives you a personalized workspace to track narratives. While we are in a researcher-first phase, registration is simplified for testing.",
      tips: ["Check your email for confirmation prompts.", "Ensure you use a secure password."]
    },
    {
      title: "Exploring the Dashboard",
      icon: LayoutDashboard,
      content: "The main Dashboard is your central hub. Here, you'll see 'Narrative Clusters'—related news stories grouped by our AI. Use the search bar to filter by tags like 'Tech', 'Geopolitics', or 'Finance'.",
      tips: ["Click on any card to see full article details.", "Look for the Credibility Score (0-100) on each card."]
    },
    {
      title: "Self-Service Analysis",
      icon: Search,
      content: "Have a news snippet or a claim from social media? Navigate to the 'Legitimacy Analyzer'. Paste the text into the input field and click 'Run Analysis'. The system will cross-reference your text against our 50+ article database.",
      tips: ["Informal or broken English is supported.", "The AI will highlight missing context."]
    },
    {
      title: "Reading Signal Reports",
      icon: Zap,
      content: "Every analysis generates an 'AI Reasoning Report'. This explains WHY the system gave a certain score. It factors in how many sources agree with you and how reliable those sources are.",
      tips: ["Check the 'Signal Weights' for transparency.", "Look at 'Corroborating Sources' to find original articles."]
    },
    {
      title: "Mobile Interactions",
      icon: Smartphone,
      content: "Our platform is fully optimized for mobile devices. On smaller screens, use the simplified 'Hamburger Menu' in the top-right corner to navigate. All analyzer tools are touch-responsive.",
      tips: ["Use 'Desktop Mode' on tablets for a wider dashboard view.", "Tap 'Run' with your thumb; touch targets are oversized for comfort."]
    }
  ];

  return (
    <div className="min-h-screen bg-background text-foreground py-16 px-6">
      <div className="mx-auto max-w-4xl">
        <Link href="/docs" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-12 group">
          <ArrowLeft className="h-4 w-4 group-hover:-translate-x-1 transition-transform" />
          Back to Central Hub
        </Link>

        {/* ── Header ─────────────────────────────────────────────────── */}
        <header className="mb-20 text-center">
          <h1 className="text-4xl md:text-6xl font-black mb-6 tracking-tight">User Operations Guide</h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Everything you need to know about navigating and utilizing the 
            <span className="text-foreground font-semibold"> Narractive Inteligence Analyzer</span> from Step 1 to Mastery.
          </p>
        </header>

        {/* ── Steps ──────────────────────────────────────────────────── */}
        <div className="space-y-12">
          {/* Signal Legend */}
          <div className="p-8 rounded-[2.5rem] bg-indigo-500/5 border border-indigo-500/20 mb-12">
            <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
              <ShieldCheck className="h-5 w-5 text-indigo-500" />
              Interpreting the Brackets
            </h3>
            <div className="grid sm:grid-cols-3 gap-4">
              {[
                { range: "90–100", label: "Highly Verified", color: "text-emerald-500" },
                { range: "70–89", label: "Corroborated", color: "text-sky-500" },
                { range: "0–69", label: "Context Missing", color: "text-amber-500" },
              ].map(b => (
                <div key={b.range} className="p-4 rounded-xl bg-card border border-border shadow-sm">
                  <div className={`text-lg font-black ${b.color}`}>{b.range}</div>
                  <div className="text-xs text-muted-foreground font-bold uppercase tracking-wider">{b.label}</div>
                </div>
              ))}
            </div>
            <p className="mt-6 text-sm text-muted-foreground/60 italic">
              Scores are generated by matching claim specificity against verified source density.
            </p>
          </div>

          {steps.map((step, i) => (
            <div key={i} className="relative pl-12 md:pl-20">
              {/* Number line */}
              <div className="absolute left-0 top-0 h-full w-px bg-border ml-4 md:ml-8"></div>
              <div className="absolute left-0 top-4 h-8 w-8 md:h-10 md:w-10 rounded-xl bg-indigo-500 flex items-center justify-center font-black text-white text-sm md:text-base z-10 shadow-lg shadow-indigo-500/20">
                {i + 1}
              </div>

              <div className="bg-card border border-border rounded-[2rem] p-8 md:p-12 hover:border-indigo-500/30 transition-colors shadow-sm">
                <div className="flex items-center gap-4 mb-6">
                  <step.icon className="h-6 w-6 text-indigo-500" />
                  <h2 className="text-2xl font-bold">{step.title}</h2>
                </div>
                <p className="text-muted-foreground leading-relaxed mb-8 text-lg">
                  {step.content}
                </p>
                
                <div className="space-y-3 border-t border-border pt-8">
                  <div className="text-[10px] font-black text-muted-foreground/60 uppercase tracking-[0.2em] mb-4">Pro Tips & Best Practices</div>
                  {step.tips.map(tip => (
                    <div key={tip} className="flex items-center gap-3 text-sm text-foreground/80">
                      <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                      {tip}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* ── Mastery Footer ────────────────────────────────────────── */}
        <div className="mt-24 p-12 rounded-[3rem] bg-indigo-500 text-center shadow-2xl shadow-indigo-500/20">
          <h2 className="text-3xl font-black mb-4 text-white">Ready to analyze?</h2>
          <p className="text-indigo-100 mb-8 max-w-lg mx-auto">
            Now that you have the 100% guide, it's time to test your first news narrative. 
            Put the analyzer to work and find the signal in the noise.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link href="/analyze" className="w-full sm:w-auto px-8 py-4 rounded-2xl bg-white text-indigo-600 font-bold hover:scale-105 transition-transform flex items-center justify-center gap-2">
              Start Analyzer <MousePointer2 className="h-4 w-4" />
            </Link>
            <Link href="/" className="w-full sm:w-auto px-8 py-4 rounded-2xl bg-indigo-600 text-white border border-white/20 font-bold hover:bg-indigo-700 transition-all">
              Go to Dashboard
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
